// =====================================================================
// NAVRATRI — full festival config
// Ported from the original single-festival Ritkalp site
// (/Users/atulsrivastava/Claude_Code_Projects/navratri). Content is
// real, not drafted — no TODO_REVIEW markers here except where the
// original already had one (YouTube links).
// =====================================================================

import type { FestivalConfig } from "./types";

export const navratri: FestivalConfig = {
  slug: "navratri",
  nameHindi: "नवरात्रि",
  nameEnglish: "Navratri",
  seoTitle: "Navratri Puja Kits | Complete Kits Delivered to Your Doorstep",
  seoDescription:
    "आप पूजा की तैयारी करिए, बाकी सारी व्यवस्था हम कर देंगे — Order complete, handpicked Navratri puja kits and get them delivered to your doorstep. Order in seconds on WhatsApp.",

  theme: {
    primary: {
      DEFAULT: "#7A1F2B",
      50: "#FBEDEE",
      100: "#F3D3D6",
      200: "#E3A5AB",
      300: "#D07680",
      400: "#B14956",
      500: "#7A1F2B",
      600: "#671A24",
      700: "#54151E",
      800: "#411117",
      900: "#2E0C10",
    },
    accent: {
      DEFAULT: "#D4A017",
      50: "#FBF4DE",
      100: "#F6E6B4",
      200: "#EFD285",
      300: "#E7BD56",
      400: "#DFAC33",
      500: "#D4A017",
      600: "#AC8012",
      700: "#84610E",
      800: "#5C4309",
      900: "#342605",
    },
    surface: { DEFAULT: "#FDF8F0", soft: "#FAF1E1", deep: "#F3E7CF" },
  },

  hero: {
    headlineHindi: "इस नवरात्रि, पूजा की चिंता छोड़िए",
    subheadlineHindi: "आप पूजा की तैयारी करिए, बाकी सारी व्यवस्था हम कर देंगे",
    lineEnglish: "You focus on the devotion, we'll handle every item of the puja.",
    ctaShopLabel: "Shop Navratri Kits",
    ctaWhatsappLabel: "Chat on WhatsApp",
    heroImage: "/images/hero-placeholder.svg",
    trustBadges: [
      { icon: "sparkle", label: "Handpicked & Pure Ingredients" },
      { icon: "truck", label: "Pan-India Delivery" },
      { icon: "chat", label: "Order via WhatsApp — Talk to a Real Person" },
    ],
    youtubeUrl: "https://www.youtube.com/watch?v=6S0riqgKN8M",
  },

  promise: {
    eyebrow: "Our Promise",
    heading: "Devotion made simple",
    cards: [
      {
        icon: "box",
        title: "Complete Kits, No Running Around",
        description:
          "Every item you need for your puja, bundled into one kit — no more running between five shops the night before.",
      },
      {
        icon: "leaf",
        title: "Pure & Authentic Samagri",
        description:
          "Handpicked, quality-checked ingredients sourced the traditional way — nothing synthetic, nothing cut corners.",
      },
      {
        icon: "chat",
        title: "Order in Seconds via WhatsApp",
        description:
          "No accounts, no cart, no payment gateway. Tap a button, send a message, and we take it from there.",
      },
      {
        icon: "door",
        title: "Delivered to Your Doorstep",
        description:
          "Pan-India delivery, timed to reach you well before your puja day so you're never rushing.",
      },
    ],
  },

  kits: {
    eyebrow: "Shop Navratri Kits",
    heading: "Complete kits, not a checklist",
    intro:
      "Pick the kit that matches how you celebrate — from a single day's essentials to the entire nine-day journey, boxed and ready.",
    items: [
      {
        id: "complete-navratri-box",
        name: "Complete Navratri Box",
        description:
          "Everything you need for all 9 days of Navratri in one box — from Ghatasthapana to Kanya Pujan.",
        image: "/images/kits/complete-navratri-box.svg",
        items: [
          "माता दुर्गा की फोटो/मूर्ति",
          "कलश (तांबे/पीतल/मिट्टी का) व ढक्कन",
          "घटस्थापना हेतु मिट्टी का पात्र, साफ मिट्टी व जौ के बीज",
          "सप्तधान्य (सात प्रकार के अनाज)",
          "आम या अशोक के 5 पत्ते व नारियल",
          "लाल कपड़ा व माता की लाल चुनरी",
          "मौली/कलावा व दूर्वा",
          "रोली, कुमकुम, हल्दी व सिंदूर",
          "अक्षत (चावल), चंदन, सुपारी, लौंग व इलायची",
          "कपूर व धूप/अगरबत्ती",
          "घी, दीपक व रूई की बत्तियां",
          "माचिस/लाइटर",
          "फूल व गेंदे की माला",
          "फल व मिठाई/मखाने भोग",
          "पंचामृत सामग्री — दूध, दही, घी, शहद, शक्कर",
          "गंगाजल, पूजा की थाली व घंटी",
          "जल का लोटा व आसन",
          "कन्या पूजन सामग्री — चुनरी, दक्षिणा पाउच व अक्षत-रोली",
          "दुर्गा चालीसा/सप्तशती पुस्तिका",
          "सभी 9 दिनों के लिए Day-wise पूजा विधि कार्ड",
        ],
        startingPrice: 2499,
        featured: true,
        badge: "Most Popular",
      },
      {
        id: "daily-puja-kit",
        name: "Daily Puja Kit",
        description:
          "A single day's essentials, refreshed and ready — perfect if you already have the basics at home.",
        image: "/images/kits/daily-puja-kit.svg",
        items: [
          "ताज़े फूल व माला",
          "कुमकुम, अक्षत व चंदन",
          "अगरबत्ती व 2 घी के दीये",
          "रूई की बत्तियां",
          "कपूर व माचिस",
          "छोटी भोग थाली",
        ],
        startingPrice: 499,
      },
      {
        id: "kalash-sthapana-kit",
        name: "Kalash Sthapana Kit",
        description:
          "Everything for Day 1's Ghatasthapana — set up your sacred kalash correctly, without hunting for items.",
        image: "/images/kits/kalash-sthapana-kit.svg",
        items: [
          "कलश (तांबे/पीतल/मिट्टी का) व नारियल",
          "आम के पत्ते",
          "लाल कपड़ा व मौली",
          "अक्षत (साबुत चावल), सुपारी व सिक्के",
          "जौ बोने हेतु मिट्टी का पात्र व सप्तधान्य",
          "अखंड ज्योति हेतु घी का दीया",
        ],
        startingPrice: 799,
      },
      {
        id: "kanya-pujan-kit",
        name: "Kanya Pujan Kit",
        description:
          "Everything to honour the nine little goddesses on Ashtami or Navami — gifts, tilak, and thali all included.",
        image: "/images/kits/kanya-pujan-kit.svg",
        items: [
          "रोली, अक्षत व आरती थाली",
          "चुनरी सेट (9 कन्याओं तक के लिए)",
          "वापसी उपहार पाउच (return-gift)",
          "पूरी, हलवा व काले चने की सामग्री (dry-mix)",
          "शगुन हेतु सिक्के",
          "कन्या पूजन विधि कार्ड (प्रिंटेड)",
        ],
        startingPrice: 599,
      },
      {
        id: "ashtami-navami-special-kit",
        name: "Ashtami-Navami Special Kit",
        description:
          "The complete Havan and Ashtami-Navami sāmagri, so the most important days go off without a hitch.",
        image: "/images/kits/ashtami-navami-special-kit.svg",
        items: [
          "हवन कुंड सामग्री व हवन मिश्रण",
          "आम की लकड़ी/समिधा व सूखा नारियल",
          "घी व पंचमेवा (पांच प्रकार के मेवे)",
          "देवी शृंगार हेतु लाल चुनरी",
          "अतिरिक्त अगरबत्ती, धूप व कपूर",
          "हवन विधि मंत्र कार्ड",
        ],
        startingPrice: 899,
      },
      {
        id: "devi-shringar-kit",
        name: "Maa Durga Shringar Kit",
        description:
          "Decorative adornment items to dress the Devi's idol or photo beautifully through all nine days.",
        image: "/images/kits/devi-shringar-kit.svg",
        items: [
          "गोल्डन बॉर्डर वाली लाल चुनरी",
          "बिंदी, चूड़ियां व मुकुट सेट",
          "कृत्रिम गेंदे की माला",
          "सजावटी बैकड्रॉप कपड़ा",
          "छोटी LED फेयरी लाइट्स",
        ],
        startingPrice: 699,
      },
    ],
  },

  // Individual add-on items for the Kit Builder — sourced from the same
  // real मुख्य सामग्री list used in dayGuide.mainSamagri below, priced
  // and grouped into tap-to-add categories. Real content, no TODO_REVIEW.
  builder: {
    eyebrow: "अपनी किट बनाइए",
    heading: "Build Your Own Navratri Kit",
    intro:
      "एक kit चुनें, फिर जो अलग से चाहिए वह टैप करके थाली में जोड़ें — कीमत अपने आप जुड़ती जाएगी।",
    blankBaseLabel: "शुरुआत से बनाएं",
    categories: [
      {
        id: "flowers",
        label: "फूल व शृंगार",
        items: [
          { id: "loose-flowers", name: "ताज़े फूल", icon: "flower", price: 49 },
          { id: "marigold-mala", name: "गेंदे की माला", icon: "flower", price: 69 },
          { id: "red-chunri", name: "माता की लाल चुनरी", icon: "chunri", price: 99 },
          { id: "chunri-set", name: "शृंगार चुनरी सेट", icon: "chunri", price: 149 },
        ],
      },
      {
        id: "bhog",
        label: "मिठाई व भोग",
        items: [
          { id: "sweets", name: "मिठाई", icon: "sweet", price: 129 },
          { id: "fruits", name: "मौसमी फल", icon: "fruit", price: 99 },
          { id: "makhana", name: "मखाने भोग", icon: "sweet", price: 79 },
          { id: "coconut", name: "नारियल", icon: "coconut", price: 39 },
          { id: "panchamrit", name: "पंचामृत सामग्री", icon: "sweet", price: 89 },
        ],
      },
      {
        id: "essentials",
        label: "पूजा सामग्री",
        items: [
          { id: "roli-kumkum", name: "रोली, कुमकुम व हल्दी सेट", icon: "thali", price: 59 },
          { id: "akshat-chandan", name: "अक्षत व चंदन", icon: "thali", price: 39 },
          { id: "kapoor-agarbatti", name: "कपूर व अगरबत्ती", icon: "incense", price: 49 },
          { id: "ghee-diya", name: "घी के दीये (सेट)", icon: "diya", price: 89 },
          { id: "kalash-mauli", name: "कलश व मौली", icon: "kalash", price: 199 },
          { id: "gangajal", name: "गंगाजल", icon: "thali", price: 29 },
          { id: "puja-ghanti", name: "पूजा की घंटी", icon: "bell", price: 129 },
        ],
      },
      {
        id: "havan",
        label: "हवन व विशेष",
        items: [
          { id: "havan-samagri", name: "हवन सामग्री सेट", icon: "havan", price: 249 },
          { id: "saptadhanya", name: "सप्तधान्य व जौ", icon: "havan", price: 69 },
          { id: "dakshina-pouch", name: "दक्षिणा पाउच सेट (कन्या पूजन)", icon: "chunri", price: 99 },
        ],
      },
    ],
  },

  dayGuide: {
    sectionId: "nine-days",
    navLabel: "9 Days Guide",
    eyebrow: "Nau Din, Nau Roop",
    heading: "9 Days of Navratri, Explained",
    intro:
      "Each day of Navratri honours a different form of the Goddess. Tap a day to learn her significance and how it's traditionally observed.",
    mainSamagriHeading: "नवरात्रि की मुख्य सामग्री",
    mainSamagriSubheading:
      "इनमें से अधिकांश चीज़ें Day 1 से Day 9 तक रोज़ काम आएंगी — एक बार में खरीद लें।",
    mainSamagri: [
      "माता दुर्गा की फोटो/मूर्ति",
      "पूजा की चौकी",
      "लाल कपड़ा/आसन",
      "माता की लाल चुनरी",
      "मौली/कलावा",
      "रोली",
      "कुमकुम",
      "हल्दी",
      "अक्षत (चावल)",
      "चंदन",
      "सिंदूर",
      "सुपारी",
      "लौंग",
      "इलायची",
      "कपूर",
      "धूप/अगरबत्ती",
      "घी",
      "दीपक",
      "रूई की बत्तियां",
      "माचिस/लाइटर",
      "फूल",
      "माला — विशेषकर गेंदे की",
      "फल",
      "मिठाई/मखाने/नारियल आदि भोग",
      "पंचामृत की सामग्री — दूध, दही, घी, शहद, शक्कर",
      "गंगाजल",
      "पूजा की थाली",
      "घंटी",
      "शंख — यदि घर में हो",
      "जल का लोटा",
      "आसन",
    ],
    dailyQuickVidhiHeading: "रोज़ की छोटी पूजा (15–30 मिनट)",
    dailyQuickVidhi: [
      "स्नान",
      "पूजा स्थान साफ",
      "दीपक",
      "धूप",
      "गणेश स्मरण",
      "कलश पूजन",
      "उस दिन की देवी का ध्यान",
      "रोली/अक्षत/फूल",
      "भोग",
      "मंत्र जाप",
      "दुर्गा चालीसा/सप्तशती",
      "आरती",
      "प्रसाद",
    ],
    samagriNote:
      "भोग की चीज़ें और दिन के रंग/भोग की सूची अलग-अलग क्षेत्रों और परंपराओं में बदलती है — अपनी पारिवारिक परंपरा के अनुसार बदलाव करें।",
    bannerImage: "/images/nau-roop-combined.svg",
    bannerEyebrow: "Nau Din, Nau Roop",
    bannerHeading: "नवरात्रि के नौ रूप, एक साथ",
    bannerLinkText: "9 Days Guide",
    days: [
      {
        dayNumber: 1,
        dateLabel: "Day 1",
        nameHindi: "शैलपुत्री",
        nameEnglish: "Shailputri",
        epithet: "Daughter of the Mountains",
        significance:
          "Shailputri is the daughter of Himavan, the king of the mountains, and the first form of Goddess Durga worshipped during Navratri. She is depicted riding Nandi the bull, holding a trishul and a lotus. She represents the pure, untamed form of Mother Nature and symbolizes new beginnings — the same shakti that once existed as Sati is reborn here as the mountain's daughter.",
        samagri: [
          "जौ",
          "मिट्टी का पात्र",
          "कलश",
          "नारियल",
          "लाल कपड़ा",
          "आम के पत्ते",
          "सफेद/लाल फूल",
          "घी",
          "गाय के घी से बना भोग",
        ],
        vidhiSteps: [
          "सुबह स्नान करके साफ कपड़े पहनें।",
          "पूजा स्थान साफ करके चौकी पर लाल कपड़ा बिछाएं।",
          "मिट्टी के पात्र में मिट्टी डालकर जौ बोएं।",
          "उसके पास कलश स्थापित करें।",
          "कलश में जल, गंगाजल, अक्षत, सुपारी, सिक्का और इत्र डालें।",
          "ऊपर पांच पत्ते लगाकर नारियल को लाल कपड़े में लपेटकर रखें।",
          "माता दुर्गा की मूर्ति/फोटो स्थापित करें।",
          "दीपक और धूप जलाएं।",
          "गणेश जी का स्मरण करें।",
          "कलश और माता का पूजन करें।",
          "माँ शैलपुत्री को फूल, अक्षत, रोली और भोग अर्पित करें।",
          "दुर्गा सप्तशती/दुर्गा चालीसा का पाठ कर सकते हैं।",
          "अंत में माता की आरती करें।",
        ],
        mantra: "ॐ देवी शैलपुत्र्यै नमः।",
        additionalSection: {
          title: "घटस्थापना की सामग्री (Day 1 विशेष)",
          note:
            "Day 1 सबसे महत्वपूर्ण है क्योंकि इसी दिन कलश स्थापना और जौ बोना किया जाता है। घटस्थापना के बाद रोज़ इसी स्थापित कलश और जौ के सामने पूजा जारी रखी जाती है।",
          samagri: [
            "मिट्टी का चौड़ा पात्र",
            "साफ मिट्टी",
            "जौ के बीज",
            "सात प्रकार के अनाज/सप्तधान्य — पारिवारिक परंपरा अनुसार",
            "तांबे/पीतल/मिट्टी का कलश",
            "गंगाजल",
            "कलश के लिए जल",
            "5 आम के पत्ते या अशोक के पत्ते",
            "सुपारी",
            "सिक्का",
            "इत्र",
            "अक्षत",
            "नारियल",
            "लाल कपड़ा",
            "मौली",
            "दूर्वा",
            "फूल/माला",
          ],
        },
        image: "/images/devis/shailputri.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=IdFvZyd8LVU&t=30s",
        kitPrice: 799,
      },
      {
        dayNumber: 2,
        dateLabel: "Day 2",
        nameHindi: "ब्रह्मचारिणी",
        nameEnglish: "Brahmacharini",
        epithet: "The Ascetic Form",
        significance:
          "Brahmacharini is the unmarried, ascetic form of the Goddess, shown walking barefoot and carrying a rosary (japamala) and a kamandalu (water pot). Her name literally means 'she who practises austerity.' She represents penance, discipline, and unwavering devotion — the long tapasya she performed to win Lord Shiva as her husband.",
        samagri: ["सफेद फूल", "मिश्री", "शक्कर", "फल", "दूध/दूध से बनी चीज़"],
        vidhiSteps: [
          "सुबह स्नान करके पूजा स्थान साफ करें।",
          "दीपक और धूप जलाएं।",
          "कलश और माता को प्रणाम करें।",
          "माँ ब्रह्मचारिणी को फूल, अक्षत, रोली अर्पित करें।",
          "मिश्री/शक्कर का भोग लगाएं।",
          "मंत्र का जाप करें।",
          "दुर्गा चालीसा या दुर्गा सप्तशती का पाठ करें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी ब्रह्मचारिण्यै नमः।",
        image: "/images/devis/brahmacharini.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=-C80VME4NF4",
        kitPrice: 299,
      },
      {
        dayNumber: 3,
        dateLabel: "Day 3",
        nameHindi: "चन्द्रघण्टा",
        nameEnglish: "Chandraghanta",
        epithet: "The Married, Warrior Form",
        significance:
          "Chandraghanta is the married form of Parvati, so named for the half-moon (chandra) shaped like a bell (ghanta) that she bears on her forehead. Golden-complexioned and ten-armed, she rides a tiger and carries weapons in each hand. She symbolizes courage and grace in the face of evil, ever ready to battle injustice while remaining a source of peace for her devotees.",
        samagri: ["दूध", "खीर", "सफेद/पीले फूल", "फल", "मिठाई", "कपूर"],
        vidhiSteps: [
          "दीपक और धूप जलाएं।",
          "माता चंद्रघंटा का ध्यान करें।",
          "रोली, अक्षत और फूल चढ़ाएं।",
          "दूध या खीर का भोग लगाएं।",
          "मंत्र का जाप करें।",
          "दुर्गा चालीसा/सप्तशती पाठ करें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी चन्द्रघण्टायै नमः।",
        image: "/images/devis/chandraghanta.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=obyot4mcpfI",
        kitPrice: 349,
      },
      {
        dayNumber: 4,
        dateLabel: "Day 4",
        nameHindi: "कूष्माण्डा",
        nameEnglish: "Kushmanda",
        epithet: "Creator of the Universe",
        significance:
          "Kushmanda is believed to have created the entire universe with just her radiant smile, at a time when there was nothing but darkness. Her name combines 'ku' (a little), 'ushma' (warmth/energy) and 'anda' (the cosmic egg) — she is the source of the sun's own radiance and resides at its core. She represents cosmic energy, creation, and the life force behind all existence.",
        samagri: [
          "मालपुआ/मीठा भोग",
          "कद्दू/पेठा — अपनी परंपरा के अनुसार",
          "फूल",
          "फल",
          "नारियल",
          "मिठाई",
        ],
        vidhiSteps: [
          "माता को प्रणाम करके दीपक जलाएं।",
          "फूल और अक्षत चढ़ाएं।",
          "कूष्मांडा माता को भोग अर्पित करें।",
          "मंत्र का जाप करें।",
          "दुर्गा चालीसा/सप्तशती का पाठ करें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी कूष्माण्डायै नमः।",
        image: "/images/devis/kushmanda.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=ALx3lSs6CqQ",
        kitPrice: 349,
      },
      {
        dayNumber: 5,
        dateLabel: "Day 5",
        nameHindi: "स्कन्दमाता",
        nameEnglish: "Skandamata",
        epithet: "Mother of Skanda (Kartikeya)",
        significance:
          "Skandamata is worshipped as the mother of Skanda (also known as Kartikeya or Murugan), the commander of the divine army. She is depicted seated on a lotus, holding her infant son in her lap. She represents maternal love, nurturing, and fierce protection — the same strength that lets a mother stand between her child and any danger.",
        samagri: [
          "केले",
          "केले से बना भोग",
          "पीले या सफेद फूल",
          "फल",
          "मिठाई",
          "पंचामृत",
        ],
        vidhiSteps: [
          "पूजा स्थान पर दीपक और धूप जलाएं।",
          "माता स्कंदमाता को फूल और अक्षत अर्पित करें।",
          "केले का भोग लगाएं।",
          "माता का ध्यान और मंत्र जाप करें।",
          "दुर्गा चालीसा/सप्तशती पढ़ें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी स्कन्दमात्रे नमः।",
        image: "/images/devis/skandamata.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=KuLf5MtdWuE",
        kitPrice: 349,
      },
      {
        dayNumber: 6,
        dateLabel: "Day 6",
        nameHindi: "कात्यायनी",
        nameEnglish: "Katyayani",
        epithet: "The Fierce Warrior",
        significance:
          "Katyayani was born to the sage Katyayan through his penance, and later merged the combined energies of the gods to battle the demon Mahishasura. Fierce and radiant, she rides a lion and carries a sword. She represents courage, valour, and the destruction of evil — a reminder that righteous anger, rightly directed, is itself a form of devotion.",
        samagri: [
          "लाल फूल",
          "शहद",
          "फल",
          "मिठाई",
          "लाल चुनरी/लाल वस्त्र — यदि चढ़ाना हो",
          "सिंदूर",
        ],
        vidhiSteps: [
          "दीपक और धूप जलाएं।",
          "माता कात्यायनी को लाल फूल अर्पित करें।",
          "सिंदूर और अक्षत अर्पित करें।",
          "शहद का भोग लगाएं।",
          "मंत्र जाप करें।",
          "दुर्गा चालीसा/सप्तशती का पाठ करें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी कात्यायन्यै नमः।",
        image: "/images/devis/katyayani.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=fm0LR9UEGck",
        kitPrice: 349,
      },
      {
        dayNumber: 7,
        dateLabel: "Day 7",
        nameHindi: "कालरात्रि",
        nameEnglish: "Kalaratri",
        epithet: "The Destroyer of Darkness",
        significance:
          "Kalaratri is the fiercest of the nine forms — dark-complexioned, dishevelled-haired, riding a donkey, with fire flashing from her nostrils. Despite her terrifying appearance, she is also called Shubhankari (the auspicious one), for she destroys ignorance, darkness, and demonic forces to protect her devotees. She represents the courage to face fear itself. यह दिन माँ के उग्र स्वरूप की पूजा का है।",
        samagri: ["गुड़", "लाल/गहरे रंग के फूल", "नारियल", "फल", "घी", "कपूर", "दीपक"],
        vidhiSteps: [
          "पूजा स्थान साफ रखें।",
          "दीपक और धूप जलाएं।",
          "माता कालरात्रि का ध्यान करें।",
          "फूल, अक्षत और रोली अर्पित करें।",
          "गुड़ का भोग लगाएं।",
          "मंत्र जाप करें।",
          "दुर्गा चालीसा/सप्तशती का पाठ करें।",
          "आरती करें।",
        ],
        mantra: "ॐ देवी कालरात्र्यै नमः।",
        image: "/images/devis/kalaratri.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=2B9oRUujRvI",
        kitPrice: 349,
      },
      {
        dayNumber: 8,
        dateLabel: "Day 8 · Ashtami",
        nameHindi: "महागौरी",
        nameEnglish: "Mahagauri",
        epithet: "The Serene, Radiant Form",
        significance:
          "Mahagauri represents Parvati after her long penance was rewarded — her skin, darkened by austerity, was washed clean and radiant by the Ganga, restoring her fair, serene form. Dressed in white and riding a bull, she embodies peace, purity, and the calm that follows the storm — forgiveness and grace after struggle. यह दिन उत्तर भारत में विशेष रूप से महत्वपूर्ण है क्योंकि कई परिवार कन्या पूजन/कंजक इसी दिन करते हैं।",
        samagri: [
          "नारियल",
          "सफेद फूल",
          "हलवा",
          "पूरी",
          "काले चने",
          "फल",
          "मिठाई",
          "चुनरी",
        ],
        vidhiSteps: [
          "माता की सामान्य पूजा करें।",
          "महागौरी को फूल, अक्षत और भोग अर्पित करें।",
          "हलवा-पूरी-चना बनाएं।",
          "कन्याओं को घर बुलाकर उनके पैर धोएं।",
          "रोली-अक्षत लगाएं।",
          "उन्हें भोजन कराएं।",
          "दक्षिणा/उपहार दें।",
          "उनके चरण स्पर्श करके आशीर्वाद लें।",
          "अंत में माता की आरती करें।",
        ],
        mantra: "ॐ देवी महागौर्यै नमः।",
        additionalSection: {
          title: "कन्या पूजन सामग्री",
          note:
            "कन्या पूजन आम तौर पर अष्टमी या नवमी को किया जाता है और नौ कन्याओं को नवदुर्गा के स्वरूप के रूप में पूजने की परंपरा है; परिवार की परंपरा के अनुसार संख्या (5/7/9) अलग हो सकती है।",
          samagri: [
            "5/7/9 कन्याओं के लिए भोजन",
            "हलवा",
            "पूरी",
            "काले चने",
            "फल/मिठाई",
            "रोली",
            "अक्षत",
            "चुनरी",
            "छोटी दक्षिणा/उपहार",
            "लड़के को बुलाने की पारिवारिक परंपरा हो तो उसके लिए भी भोजन/उपहार",
          ],
        },
        image: "/images/devis/mahagauri.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=2Pw8YuKHfDE",
        kitPrice: 599,
      },
      {
        dayNumber: 9,
        dateLabel: "Day 9 · Navami",
        nameHindi: "सिद्धिदात्री",
        nameEnglish: "Siddhidatri",
        epithet: "The Bestower of Spiritual Powers",
        significance:
          "Siddhidatri, the final form, is said to possess and bestow all eight siddhis (spiritual powers/perfections). Seated on a lotus, she represents the completion of the spiritual journey that began with Shailputri — the point at which the devotee, having moved through austerity, courage, and grace, attains fulfilment and oneness with the divine.",
        samagri: [
          "तिल",
          "नारियल",
          "फल",
          "मिठाई",
          "हलवा-पूरी-चना — यदि कन्या पूजन आज कर रहे हों",
          "फूल",
          "लाल चुनरी",
          "घी",
          "कपूर",
        ],
        vidhiSteps: [
          "स्नान करके पूजा स्थान साफ करें।",
          "दीपक और धूप जलाएं।",
          "कलश और जौ को प्रणाम करें।",
          "माँ सिद्धिदात्री को फूल, अक्षत, रोली और भोग अर्पित करें।",
          "तिल/नारियल का भोग अपनी परंपरा के अनुसार लगाएं।",
          "दुर्गा चालीसा/सप्तशती का पाठ करें।",
          "कन्या पूजन यदि नवमी को करते हैं तो करें।",
          "हवन की पारिवारिक परंपरा हो तो हवन करें।",
          "पूर्णाहुति दें।",
          "माता की आरती करें।",
        ],
        mantra: "ॐ देवी सिद्धिदात्र्यै नमः।",
        additionalSection: {
          title: "हवन सामग्री (यदि हवन करना हो)",
          samagri: [
            "हवन कुंड",
            "हवन सामग्री",
            "आम की लकड़ी/समिधा",
            "घी",
            "कपूर",
            "जौ",
            "तिल",
            "अक्षत",
            "सूखा नारियल",
            "गुग्गुल — यदि परंपरा में हो",
            "हवन चम्मच",
            "जल का पात्र",
          ],
          optional: true,
        },
        image: "/images/devis/siddhidatri.svg",
        youtubeUrl: "https://www.youtube.com/watch?v=mxbQYHbk6UI",
        kitPrice: 399,
      },
    ],
  },

  trust: {
    eyebrow: "Why Trust Us",
    heading: "Trusted Across India",
    stats: [
      { value: "500+", label: "Kits Delivered" },
      { value: "15+", label: "Cities Served" },
      { value: "4.8★", label: "Customer Rating" },
    ],
    // No testimonials yet — deliberately left empty rather than
    // filled with fabricated customer quotes/names. StatsAndTestimonials.tsx
    // hides the testimonials grid entirely when this is empty, so the
    // stats strip above still renders cleanly. Add real ones here
    // (verbatim quote + real name + real city) as they come in.
    testimonials: [],
  },

  finalCta: {
    heading: "Ready to bring home the blessings of Navratri?",
    line:
      "Message us on WhatsApp and we'll help you pick the right kit — no forms, no accounts, just a conversation.",
  },

  footerTagline: "You focus on the devotion, we'll handle every item of the puja.",
  whatsappCollectionName: "Navratri",

  about: {
    heading: "हमारे बारे में",
    tagline: "माँ की भक्ति में, आपकी सुविधा का साथ",
    paragraphs: [
      "नवरात्रि हमारे लिए सिर्फ एक त्योहार नहीं, माँ दुर्गा के प्रति आस्था और विश्वास का पर्व है।",
      "हम जानते हैं कि नवरात्रि की पूजा के लिए सही और जरूरी पूजा सामग्री जुटाना कई बार आसान नहीं होता। अलग-अलग दुकानों पर जाना, हर सामग्री ढूँढना, कुछ छूट जाने की चिंता और समय की कमी — ये छोटी-छोटी परेशानियाँ आपकी पूजा की तैयारियों को मुश्किल बना सकती हैं।",
      "हमारा उद्देश्य है कि नवरात्रि पूजा में उपयोग होने वाली जरूरी सामग्री आपको एक ही जगह आसानी से उपलब्ध हो, ताकि आपको हर चीज़ के लिए अलग-अलग जगह भटकना न पड़े।",
      "हम आपको ऐसी पूजा सामग्री उपलब्ध कराने का प्रयास करते हैं, जिससे आपकी नवरात्रि की तैयारियाँ आसान, सुविधाजनक और चिंता-मुक्त बन सकें।",
    ],
    calloutQuote: [
      "आपका समय खरीदारी में नहीं,",
      "माँ की भक्ति और पूजा में लगे — यही हमारी कोशिश है।",
    ],
    closingHeading: "आपकी आस्था, हमारी जिम्मेदारी",
    closingParagraph:
      "हर सामग्री के पीछे हमारा प्रयास यही है कि जब आप माँ की पूजा करें, तो आपके मन में सिर्फ श्रद्धा और भक्ति हो — सामान जुटाने की चिंता नहीं।",
    closingCouplet: ["नवरात्रि की तैयारी हम पर छोड़िए,", "माँ की भक्ति आप पर।"],
    finalPhrase: "जय माता दी",
  },

  dateHint: { fromMonth: 9, toMonth: 10 },
};
